symptom_dictionary = {'Vertigo': r'vertigo',
                      'Headaches': r'headaches?',
                      'Lightheadedness': r'lightheadedness',
                      'Edema': r'(?<!no\s)edema',
                      'Clubbing': r'(?<!or\s)clubbing',
                      'Rales': r'(?<!no\s)rales?',
                      'Wheezing': r'(?<!or\s)wheez(e|ing)',
                      'Hypertension': r'hypertension',
                      'Dyspnea': r'dyspnea',
                      'Cough': r'cough(ing)?',
                      'Heart murmurs': r'murmurs?',
                      'Ringing in the ears': r'ringing in( the)? ears?',
                      'Shortness of breath': r'short(ening|ness|ened)( of)? breath(ing)?',
                      'Sputum production': r'sputum production|production of sputum',
                      'Pyelonephritis': r'pyelonephritis',
                      'Hemorrhagic Stroke': r'ha?emorrhagic stroke',
                      'Lumps': r'lumps?',
                      'Diabetes': r'diabet(es|ic)',
                      'Weight loss': r'weight loss|loss of weight',
                      'Foot pain': r'foot pain',
                      'Paresthesia': r'paresthesia',
                      'Foamy urine': r'foamy urine',
                      'Tingling of the feet': r'tingling of( the)? (foot|feet)',
                      'Atherosclerotic calcification': r'atherosclerotic calcification|atherosclerosis',
                      'Frequent urination': r'frequent urinati(on|ng)',
                      'Increased thirst': r'increase(d| in) thirst',
                      'Weak urinary stream': r'weak urinary stream',
                      'Chest pain': r'chest pain|pain in( the?) chest',
                      'Hemorrhage': r'ha?emorrhage',
                      'Trauma': r'trauma',
                      'Lethargy': r'letharg(y|ic)',
                      'Swollen ankles': r'(swollen|swelling (of|at)( the)?) ankles?',
                      'Palpitations': r'palpitations?',
                      'Stump pain': r'stump pain|pain (in|at) (the )?(stump|amputation site)',
                      'Discomfort with movement': r'discomfort (with|in) mov(ement|ing)',
                      'Distress': r'distress',
                      'Urinary dribbling': r'urinary (dribbling|incontinence)',
                      'Fever': r'fever',
                      'Myocardial Infarction': r'myocardial infarction|heart attack',
                      'Swelling at the amputation site': r'(swelling|swollen) (at|in )?(the )?(amputation site|stump)',
                      'Disarticulation of the right shoulder': r'disarticulat(ion|ed) ((of|at|in)( the )? )?right shoulder',
                      'Erythema': r'erythem(a|ic)',
                      'Burned shoulder': r'burn(ed)? ((at|to|in) (the )?)?shoulder',
                      'Disarticulation of the right hip': r'disarticulat(ion|ed) ((of|at|in)( the )? )?right hip',
                      'Limb pain': r'limb pain|pain (in|at) (the )?limb'}

diagnosis_list = ['Hemorrhagic Stroke', 'Pyelonephritis', 'Embolic Stroke', 'Type 2 Diabetes',
                  'Chronic Congestive Heart Failure', 'Type 1 Diabetes', 'Chronic Renal Failure',
                  'Chronic Obstructive Pulmonary Disease', 'Kidney Stones', 'Hypertension', 'Acute Renal Failure',
                  'Myocardial Infarction']
